import re
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def filter_mlp_names(query: list[str], mlps_model: dict) -> list:
    mlp_names = []
    for mlp in list(mlps_model.keys()):
        if all(item in re.split(r'[/_]', mlp) 
            for item in query):
                mlp_names.append(mlp)
    return mlp_names

sns.set_theme()
def plot_params(params, n=6):
  fig, axs = plt.subplots(ncols=2, nrows=n)
  fig.tight_layout()
  fig.set_figwidth(15)
  fig.set_figheight(7)
  for row, module in enumerate(sorted(params)):
    ax = axs[row][0]
    try:
        sns.heatmap(params[module]["w"], cmap="YlGnBu", ax=ax)
        ax.title.set_text(f"{module}/w")
    except KeyError:
        scale = np.expand_dims(params[module]["scale"], axis=0)
        sns.heatmap(scale, cmap="YlGnBu", ax=ax)
        ax.title.set_text(f"{module}/scale")

    ax = axs[row][1]
    try:
        b = np.expand_dims(params[module]["b"], axis=0)
        sns.heatmap(b, cmap="YlGnBu", ax=ax)
        ax.title.set_text(f"{module}/b")
    except KeyError:
        b = np.expand_dims(params[module]["offset"], axis=0)
        sns.heatmap(b, cmap="YlGnBu", ax=ax)
        ax.title.set_text(f"{module}/offset")

class Params_tree:
    """
    Class to give to the params generated by GraphCast a tree structure
    """
    def __init__(self, graphcast_params):
        self.params = graphcast_params
        tree = {}
        # Generate permutations of ['grid2mesh', 'mesh2grid']
        grid2mesh_mesh2grid_mlps_names = []
        # Iterate over permutations
        for q in ['grid2mesh', 'mesh2grid']:
            # list_cum_q = list(q)
            names = filter_mlp_names(query=[q], mlps_model=graphcast_params)
            grid2mesh_mesh2grid_mlps_names.extend(names)
            n = len(names)
            tree[q] = [n, {}]
            
            # Generate permutations of the current key and ['encoder', 'processor', 'decoder']
            for key1 in ['encoder', 'processor', 'decoder']:
                names = filter_mlp_names(query=[q, key1], mlps_model=graphcast_params)
                n = len(names)
                tree[q][-1][key1] = [n, {}]
                # Generate permutations of the current key and ['encoder', 'processor', 'decoder']
                for key2 in ['nodes', 'edges']:
                    names = filter_mlp_names(query=[q, key1, key2], mlps_model=graphcast_params)
                    n = len(names)
                    #print(tree[q][-1])
                    tree[q][-1][key1][-1][key2] = [n, {}]
                    for key3 in ['norm', 'linear']:
                        names = filter_mlp_names(query=[q, key1, key2, key3], mlps_model=graphcast_params)
                        n = len(names)
                        #print([q, key1, key2])
                        # print(key2)
                        tree[q][-1][key1][-1][key2][-1][key3] = [n]
                        for name in names:
                            params_dic = graphcast_params[name]
                            params_size_dic = {key + '_size': value.shape
                                               for key, value in params_dic.items()}
                            tree[q][-1][key1][-1][key2][-1][key3].append(params_size_dic)

        mesh_names = sorted(list(set(graphcast_params.keys()) - set(grid2mesh_mesh2grid_mlps_names)))
        mesh_params_per_epoch = {key: graphcast_params[key] for key in mesh_names}
        tree['mesh'] = [len(mesh_params_per_epoch), {}] 
        for key1 in ['encoder', 'processor', 'decoder']:
            names = filter_mlp_names(query=[key1], mlps_model=mesh_params_per_epoch)
            n = len(names)
            tree['mesh'][-1][key1] = [n, {}]
            for key2 in ['nodes', 'edges']:
                    names = filter_mlp_names(query=[key1, key2], mlps_model=mesh_params_per_epoch)
                    n = len(names)
                    #print(tree[q[0]][-1])
                    tree['mesh'][-1][key1][-1][key2] = [n, {}]
                    for key3 in ['norm', 'linear']:
                        names = filter_mlp_names(query=[key1, key2, key3], mlps_model=mesh_params_per_epoch)
                        n = len(names)
                        #print([q[0], key1, key2])
                        # print(key2)
                        tree['mesh'][-1][key1][-1][key2][-1][key3] = [n]
                        for name in names:
                            params_dic = graphcast_params[name]
                            params_size_dic = {key + '_size': value.shape 
                                               for key, value in params_dic.items()}
                            tree['mesh'][-1][key1][-1][key2][-1][key3].append(params_size_dic)

        self.tree = tree 

    def plot(self, n=6):
        mlps_list = np.random.choice(list(self.params.keys()), n)
        self.random_choice_params = {mlp: self.params[mlp] for mlp in mlps_list}
        return plot_params(self.random_choice_params, n)






